# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
log_level: 1

grpc_server:
  address: "127.0.0.1:9115"  # required

grpc_log:
  level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  verbosity: 99

metrics_server:
  enabled: true
  address: "127.0.0.1:9215" # required when enabled is true
  url_path: "/metrics"

hdfs_server:
  addresses: "192.168.128.12:9000"
  user_name: "root"
  buffer_size: 1024

tracer:
  service_name: "logmanager"
  local_agent: "127.0.0.1:6831"