# 1=>"debug", 2=>"info", 3=>"warn", 4=>"error", 5=>"fatal"
log_level: 1

grpc_server:
  address: "127.0.0.1:11001"  # required
  log_level: 2 #  1 => info, 2 => waring, 3 => error, 4 => fatal
  log_verbosity: 99

metrics_server:
  enabled: true
  address: "127.0.0.1:11002" # required when enabled is true
  url_path: "/metrics"

kafka_config:
  brokers: "192.168.100.3:9092,192.168.100.4:9092,192.168.100.5:9092"
  topic_regexp: "0804_test_topic"
  refresh_frequency: 10
  offsets_initial: -2
  balance_strategy: "sticky"
  group_id: "new_consumer_group_1"
  batch_mode: true
  batch_max: 512

es_config:
  urls: "http://192.168.100.14:9200,http://192.168.100.15:9200"
  index_name: "test_es_index"
  shards_num: 3
  replica_num: 1

tracer:
  service_name: "logmanager"
  local_agent: "127.0.0.1:6831"